name: 'EIC CernVM-FS Spack'
description: 'Load the EIC Spack software stack on /cvmfs/eic.opensciencegrid.org'
branding:
  icon: 'database'
inputs:
  cvmfs_repositories:
    description: 'list of cvmfs repositories to load'
    required: false
    default: 'atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch'
  cvmfs_http_proxy:
    description: 'proxy for cvmfs repositories'
    required: false
    default: 'DIRECT'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/setup-cvmfs.sh ${{ inputs.cvmfs_repositories }}
      shell: bash
